branches:
  only:
    - development-app

os:
  - linux
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid-fallback
before_script:
  - git clone https://github.com/flutter/flutter.git -b master
script:
  - cd ./frontend/apps/bookology/
  - $HOME/flutter/bin/flutter pub get
  - $HOME/flutter/bin/flutter analyze
  - $HOME/flutter/bin/flutter test
cache:
  directories:
    - $HOME/.pub-cache