FROM node:16-alpine

ARG DOMAIN_NAME
ARG MONGO_URI
ARG ACCESS_TOKEN
ARG GOOGLE_APPLICATION_CREDENTIALS
ARG CLOUD_STORAGE_BUCKET_NAME
ARG ENCRYPTION_KEY
ARG JWT_SECRET_TOKEN
ARG JWT_EMAIL_VERIFICATION_TOKEN
ARG SENDGRID_API_KEY
ARG SENDGRID_WELCOME_TEMPLATE_ID
ARG SENDGRID_DELETE_TEMPLATE_ID
ARG SENDER_ID

ENV SERVER_PORT=3000
ENV DOMAIN_NAME=$DOMAIN_NAME
ENV MONGO_URI=$MONGO_URI
ENV ACCESS_TOKEN=$ACCESS_TOKEN
ENV GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
ENV CLOUD_STORAGE_BUCKET_NAME=$CLOUD_STORAGE_BUCKET_NAME
ENV ENCRYPTION_KEY=$ENCRYPTION_KEY
ENV JWT_SECRET_TOKEN=$JWT_SECRET_TOKEN
ENV JWT_EMAIL_VERIFICATION_TOKEN=$JWT_EMAIL_VERIFICATION_TOKEN
ENV SENDGRID_API_KEY=$SENDGRID_API_KEY
ENV SENDGRID_WELCOME_TEMPLATE_ID=$SENDGRID_WELCOME_TEMPLATE_ID
ENV SENDGRID_DELETE_TEMPLATE_ID=$SENDGRID_DELETE_TEMPLATE_ID
ENV SENDER_ID=$SENDER_ID

WORKDIR /users/docker/projects/bookology/api

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]
