name: bookology
description: The Mobile App for the Bookology
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  google_mobile_ads:
    git:
      url: https://github.com/SuaMusica/googleads-mobile-flutter.git
      path: packages/google_mobile_ads
      ref: feature/suamusica
  http: ^0.13.3
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.0
  cloud_firestore: ^2.5.1
  provider: ^6.0.0
  google_fonts: ^2.1.0
  font_awesome_flutter: ^9.1.0
  google_sign_in: ^5.1.0
  flutter_dotenv: ^5.0.2
  flutter_svg: ^0.22.0
  barcode_scan2: ^4.1.4
  cached_network_image: ^3.1.0
  image_picker: ^0.8.4
  photo_view: ^0.12.0
  pull_to_refresh: ^2.0.0
  liquid_progress_indicator_ns: ^1.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  geolocator: ^7.6.0
  geocoding: ^2.0.1
  firebase_messaging: ^10.0.6
  flutter_local_notifications: ^8.1.1+2
  flutter_typeahead: ^3.2.0
  image_cropper: ^1.4.1
  cross_file: ^0.3.1+4
  firebase_storage: ^10.0.3
  shimmer: ^2.0.0
  get_storage: ^2.0.3
  flutter_firebase_chat_core: ^1.3.1
  flutter_chat_ui: ^1.3.2
  path_provider: ^2.0.3
  open_file: ^3.2.1
  mime: ^1.0.0
  file_picker: ^4.0.1
  connectivity_plus: ^1.1.0
  introduction_screen: ^2.1.0
  after_layout: ^1.1.0
  badges: ^2.0.1
  adaptive_theme: ^2.2.0
  bottom_navy_bar: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.1
flutter:
  uses-material-design: true
  assets:
    - app.config.env
    - assets/svg/google_logo.svg
    - assets/svg/verify_email.svg
    - assets/svg/books.svg
    - assets/svg/empty_list.svg
    - assets/svg/chats.svg
    - assets/svg/offline.svg
    - assets/svg/help.svg
    - assets/svg/location.svg
    - assets/svg/profile.svg
    - assets/svg/done.svg
    - assets/svg/hero.svg
    - assets/icons/bookology.icon.png

  fonts:
    - family: YoutubeSans
      fonts:
        - asset: fonts/youtube-sans-light.ttf
        - asset: fonts/youtube-sans-medium.ttf
        - asset: fonts/youtube-sans-bold.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/bookology.icon.png"