name: bookology
description: The Mobile Application for the Bookology.
publish_to: 'none'
version: 0.0.2+2

environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  google_mobile_ads: ^0.13.5
  http: ^0.13.4
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.3
  cloud_firestore: ^2.5.3
  provider: ^6.0.1
  google_fonts: ^2.1.0
  font_awesome_flutter: ^9.1.0
  google_sign_in: ^5.1.1
  flutter_svg: ^0.23.0+1
  barcode_scan2: ^4.1.4
  cached_network_image: ^3.1.0
  image_picker: ^0.8.4+2
  photo_view: ^0.12.0
  pull_to_refresh: ^2.0.0
  liquid_progress_indicator_ns: ^1.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  geolocator: ^7.7.0
  geocoding: ^2.0.1
  firebase_messaging: ^10.0.8
  flutter_local_notifications: ^9.0.0
  flutter_typeahead: ^3.2.1
  image_cropper: ^1.4.1
  cross_file: ^0.3.1+5
  firebase_storage: ^10.0.5
  shimmer: ^2.0.0
  get_storage: ^2.0.3
  flutter_firebase_chat_core: ^1.4.2
  flutter_chat_ui: ^1.4.4
  path_provider: ^2.0.5
  open_file: ^3.2.1
  mime: ^1.0.0
  file_picker: ^4.1.3
  connectivity_plus: ^2.0.2
  introduction_screen: ^2.1.0
  after_layout: ^1.1.0
  badges: ^2.0.1
  bottom_navy_bar: ^6.0.0
  package_info: ^2.0.2
  permission_handler: ^8.2.2
  dio: ^4.0.0
  fluttertoast: ^8.0.8
  share_plus: ^3.0.2
  flutter_secure_storage: ^4.2.1
  flutter_dotenv: ^5.0.2
  sentry_flutter: ^6.0.1
  intl: ^0.17.0
  bubble: ^1.2.1
  adaptive_theme: ^2.3.0
  local_auth: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.4

flutter:
  uses-material-design: true
  assets:
    - app.config.env
    - assets/svg/google_logo.svg
    - assets/svg/verify_email.svg
    - assets/svg/books.svg
    - assets/svg/empty_list.svg
    - assets/svg/chats.svg
    - assets/svg/offline.svg
    - assets/svg/help.svg
    - assets/svg/location.svg
    - assets/svg/profile.svg
    - assets/svg/done.svg
    - assets/svg/hero.svg
    - assets/svg/error.svg
    - assets/icons/bookology.icon.png
    - assets/icons/bookology.svg
    - assets/icons/splash.icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/bookology.svg"
