name: bookology
description: The Mobile App for the Bookology
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_mobile_ads:
    git:
      url: https://github.com/SuaMusica/googleads-mobile-flutter.git
      path: packages/google_mobile_ads
      ref: feature/suamusica
  http: ^0.13.3
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  cloud_firestore: ^2.3.0
  provider: ^5.0.0
  google_fonts: ^2.1.0
  font_awesome_flutter: ^9.1.0
  google_sign_in: ^5.0.4
  flutter_dotenv: ^5.0.0
  flutter_svg: ^0.22.0
  url_launcher: ^6.0.9
  barcode_scan2: ^4.1.3
  cached_network_image: ^3.0.0
  image_picker: ^0.8.1+3
  photo_view: ^0.11.1
  shared_preferences: ^2.0.6
  pull_to_refresh: ^2.0.0
  liquid_progress_indicator_ns: ^1.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  geolocator: ^7.2.0+1
  geocoding: ^2.0.0
  firebase_messaging: ^10.0.3
  flutter_local_notifications: ^6.0.0
  flutter_typeahead: ^3.2.0
  image_cropper: ^1.4.1
  cross_file: ^0.3.1+4
  firebase_storage: ^10.0.1
  shimmer: ^2.0.0
  get_storage: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - app.config.env
    - assets/svg/google_logo.svg
    - assets/svg/verify_email.svg
    - assets/svg/books.svg