name: bookology
description: The Mobile App For Bookology.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  cloud_firestore: ^2.3.0
  provider: ^5.0.0
  google_fonts: ^2.1.0
  font_awesome_flutter: ^9.1.0
  google_sign_in: ^5.0.4
  flutter_dotenv: ^5.0.0
  flutter_svg: ^0.22.0
  url_launcher: ^6.0.9
  barcode_scan2: ^4.1.3
  cached_network_image: ^3.0.0
  image_picker: ^0.8.1+3
  photo_view: ^0.11.1
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - app.config.env
    - assets/svg/google_logo.svg
    - assets/svg/verify_email.svg
    - assets/svg/books.svg
