name: bookology
description: The Mobile Application for the Bookology.
publish_to: 'none'
version: 0.0.3+3

environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  google_mobile_ads: ^1.0.0
  http: ^0.13.4
  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  cloud_firestore: ^2.5.4
  provider: ^6.0.1
  google_fonts: ^2.1.0
  font_awesome_flutter: ^9.2.0
  google_sign_in: ^5.2.1
  flutter_svg: ^0.23.0+1
  barcode_scan2: ^4.1.4
  cached_network_image: ^3.2.0
  image_picker: ^0.8.4+4
  photo_view: ^0.13.0
  pull_to_refresh: ^2.0.0
  liquid_progress_indicator_ns: ^1.0.0
  auto_size_text: ^3.0.0
  geolocator: ^8.0.0
  geocoding: ^2.0.1
  firebase_messaging: ^11.1.0
  flutter_local_notifications: ^9.1.4
  flutter_typeahead: ^3.2.3
  image_cropper: ^1.4.1
  cross_file: ^0.3.2
  firebase_storage: ^10.1.0
  shimmer: ^2.0.0
  get_storage: ^2.0.3
  flutter_firebase_chat_core: ^1.5.0
  flutter_chat_ui: ^1.5.2
  path_provider: ^2.0.7
  open_file: ^3.2.1
  mime: ^1.0.1
  file_picker: ^4.2.7
  connectivity_plus: ^2.1.0
  introduction_screen: ^2.1.0
  after_layout: ^1.1.0
  badges: ^2.0.2
  bottom_navy_bar: ^6.0.0
  package_info: ^2.0.2
  permission_handler: ^8.3.0
  dio: ^4.0.4
  fluttertoast: ^8.0.8
  share_plus: ^3.0.4
  flutter_secure_storage: ^5.0.2
  flutter_dotenv: ^5.0.2
  sentry_flutter: ^6.1.2
  intl: ^0.17.0
  bubble: ^1.2.1
  local_auth: ^1.1.8
  flutter_slidable: ^1.1.0
  blobs: ^2.0.0
  firebase_app_check: ^0.0.3
  flutter_app_feedback: ^0.0.3
  simple_animations: ^4.0.1
  dynamic_color: ^0.1.0
  animated_text_kit: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.2

flutter:
  uses-material-design: true
  assets:
    - app.config.env
    - assets/svg/google_logo.svg
    - assets/svg/verify_email.svg
    - assets/svg/books.svg
    - assets/svg/empty_list.svg
    - assets/svg/chats.svg
    - assets/svg/offline.svg
    - assets/svg/help.svg
    - assets/svg/location.svg
    - assets/svg/profile.svg
    - assets/svg/done.svg
    - assets/svg/hero.svg
    - assets/svg/error.svg
    - assets/icons/bookology.icon.png
    - assets/icons/bookology.icon.svg
    - assets/icons/bookology.splash.dark.png
    - assets/icons/bookology.splash.light.png
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Black.ttf
        - asset: fonts/poppins/Poppins-BlackItalic.ttf
        - asset: fonts/poppins/Poppins-Bold.ttf
        - asset: fonts/poppins/Poppins-BoldItalic.ttf
        - asset: fonts/poppins/Poppins-ExtraBold.ttf
        - asset: fonts/poppins/Poppins-ExtraBoldItalic.ttf
        - asset: fonts/poppins/Poppins-ExtraLight.ttf
        - asset: fonts/poppins/Poppins-ExtraLightItalic.ttf
        - asset: fonts/poppins/Poppins-Italic.ttf
        - asset: fonts/poppins/Poppins-Light.ttf
        - asset: fonts/poppins/Poppins-LightItalic.ttf
        - asset: fonts/poppins/Poppins-Medium.ttf
        - asset: fonts/poppins/Poppins-Medium.ttf
        - asset: fonts/poppins/Poppins-MediumItalic.ttf
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-SemiBold.ttf
        - asset: fonts/poppins/Poppins-SemiBoldItalic.ttf
        - asset: fonts/poppins/Poppins-Thin.ttf
        - asset: fonts/poppins/Poppins-ThinItalic.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/bookology.icon.png"
