name: Ruby

on:
  push:
    branches:
      - production-app

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [ '3.0' ]

    steps:
      - uses: actions/checkout@v2
      - name: Install & Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install & Setup Flutter SDK
        uses: subosito/flutter-action@master
      - name: Install & Setup Ruby
        uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: 'Create Google Services File'
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: /home/runner/work/bookology/bookology/frontend/apps/bookology/android/app/src/google-services.json
          FILE_BASE64: ${{ secrets.BOOKOLOGY_PRODUCATION_APP_GOOGLE_SERVICES }}
      - name: 'Create App Configurations File'
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: ${{ github.workspace }}/frontend/apps/bookology/app.config.env
          FILE_BASE64: ${{ secrets.BOOKOLOGY_PRODUCATION_APP_CONFIGURATIONS }}
      - name: 'Create Key Properties File'
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: ${{ github.workspace }}/frontend/apps/bookology/android/key.properties
          FILE_BASE64: ${{ secrets.BOOKOLOGY_PRODUCTION_APP_KEY_PROPERTIES }}
      - name: 'Create Android Signing KeyStore'
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: ${{ github.workspace }}/frontend/apps/bookology/android/app/release.jks
          FILE_BASE64: ${{ secrets.BOOKOLOGY_PRODUCTION_APP_KEY_STORE }}
      - uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'build'
          subdirectory: './frontend/apps/bookology/android/'
      - name: Create the Atrifact from the Compiled Source
        uses: actions/upload-artifact@v2
        with:
          name: Bookology-Production-App-Version-${{ secrets.BOOKOLOGY_PRODUCATION_APP_VERSION }}
          path: ${{ github.workspace }}/frontend/apps/bookology/build/app/outputs/bundle/release/
          retention-days: 7
      - name: Create A Release Of Build On GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}/frontend/apps/bookology/CHANGELOG.md
          tag_name: Bookology Version-${{ secrets.BOOKOLOGY_PRODUCATION_APP_VERSION }}
          files: ${{ github.workspace }}/frontend/apps/bookology/build/app/outputs/bundle/release/app-release.aab

